name: rxjava3

on:
  push:
    paths:
      - "rxjava3/**"
    branches:
      - master
  pull_request:
    paths:
      - "rxjava3/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'maven'
          
      - name: Start up databases via Docker Compose 
        run: |
            docker compose up -d postgres
            docker ps -a          
        
      - name: Test with CURL
        run: |
            mvn clean package exec:java -DskipTests --file rxjava3/pom.xml & 
            sleep 10
            echo ">>> print cURL result <<<"
            curl http://localhost:8888/hello & 
      
      - name: Build rxjava3
        run: mvn clean install --file rxjava3/pom.xml      
